import { Navigate, Route, Routes } from 'react-router-dom'
import ProtectedRoute from './components/ProtectedRoute'
import { useAuth } from './context/AuthContext'
import Login from './pages/Login'
import AdminDashboard from './pages/admin/AdminDashboard'
import ManageDepartments from './pages/admin/ManageDepartments'
import ManageClasses from './pages/admin/ManageClasses'
import ManageSubjects from './pages/admin/ManageSubjects'
import ManageFaculty from './pages/admin/ManageFaculty'
import ManageStudents from './pages/admin/ManageStudents'
import CorrectionApprovals from './pages/admin/CorrectionApprovals'
import Reports from './pages/admin/Reports'
import FacultyDashboard from './pages/faculty/FacultyDashboard'
import MySessions from './pages/faculty/MySessions'
import MarkAttendance from './pages/faculty/MarkAttendance'
import RequestCorrection from './pages/faculty/RequestCorrection'
import FacultyReports from './pages/faculty/FacultyReports'
import StudentDashboard from './pages/student/StudentDashboard'
import MyAttendance from './pages/student/MyAttendance'
import AttendanceCalendar from './pages/student/AttendanceCalendar'
import Navbar from './components/Navbar'
import Sidebar from './components/Sidebar'
function Shell() { return <div className="app-shell"><Navbar /><div className="body-shell"><Sidebar /><main className="main-content"><Routes><Route path="/admin" element={<AdminDashboard />} /><Route path="/admin/departments" element={<ManageDepartments />} /><Route path="/admin/classes" element={<ManageClasses />} /><Route path="/admin/subjects" element={<ManageSubjects />} /><Route path="/admin/faculty" element={<ManageFaculty />} /><Route path="/admin/students" element={<ManageStudents />} /><Route path="/admin/corrections" element={<CorrectionApprovals />} /><Route path="/admin/reports" element={<Reports />} /><Route path="/faculty" element={<FacultyDashboard />} /><Route path="/faculty/sessions" element={<MySessions />} /><Route path="/faculty/mark" element={<MarkAttendance />} /><Route path="/faculty/correction" element={<RequestCorrection />} /><Route path="/faculty/reports" element={<FacultyReports />} /><Route path="/student" element={<StudentDashboard />} /><Route path="/student/attendance" element={<MyAttendance />} /><Route path="/student/calendar" element={<AttendanceCalendar />} /></Routes></main></div></div> }
export default function App() { const { user } = useAuth(); return <Routes><Route path="/login" element={<Login />} /><Route element={<ProtectedRoute />}><Route path="/*" element={<Shell />} /></Route><Route path="*" element={<Navigate to={user ? `/${user.role}` : '/login'} replace />} /></Routes> }
